# fly.toml app configuration file generated for fresh-app-cris on 2025-10-02T08:57:58-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fresh-app-cris'
primary_region = 'gru'

[build]

[env]
  PORT = '3000'
  SCOPES = 'write_products'
  SHOPIFY_API_KEY = '88ac1c4526a866af76be341d29526cf2'
  SHOPIFY_APP_URL = 'https://fresh-app-cris.fly.dev'

[processes]
  app = 'node ./dbsetup.js npm run docker-start'

[[mounts]]
  source = 'data'
  destination = '/data'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = '1GB'
  auto_extend_size_limit = '10GB'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
