# fly.toml app configuration file generated for pencil-shop-miami on 2025-10-15T16:13:22-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pencil-shop-miami'
primary_region = 'ams'

[build]

[env]
  DATABASE_URL = 'file:/data/production.sqlite'
  PORT = '3000'
  SCOPES = 'read_inventory,read_products,read_publications,write_inventory,write_product_listings,write_products,write_publications'
  SHOPIFY_API_KEY = '168e3fcb8081159166a95d3fe1509f56'
  SHOPIFY_APP_URL = 'https://pencil-shop-miami.fly.dev'

[processes]
  app = 'node ./dbsetup.js npm run docker-start'

[[mounts]]
  source = 'data'
  destination = '/data'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = '1GB'
  auto_extend_size_limit = '10GB'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
