# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "083e72c4309ebc15af670292fc106d87"
name = "pencil-shop-dev"
application_url = "https://pencil-shop-dev.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,write_product_listings,read_inventory,write_inventory,read_publications,write_publications"

[auth]
redirect_urls = [
  "https://pencil-shop-dev.fly.dev/auth/callback",
  "https://pencil-shop-dev.fly.dev/auth/shopify/callback",
  "https://pencil-shop-dev.fly.dev/api/auth/callback"
]

[app_proxy]
url = "https://pencil-shop-dev.fly.dev"
subpath = "proxy"
prefix = "apps"
