# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "083e72c4309ebc15af670292fc106d87"
name = "pencil-shop-dev"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_products,read_publications,write_inventory,write_product_listings,write_products,write_publications"

[auth]
redirect_urls = [
  "https://example.com/api/auth",
  "https://example.com/auth",
  "https://example.com/auth/callback"
]

[app_proxy]
url = "https://example.com/proxy"
subpath = "designer"
prefix = "apps"
